import React, { useEffect, useState } from 'react';
import { useLocation, Link } from 'react-router-dom';
import { Shield, FileText, CheckCircle, Lock, Users, Globe, ExternalLink, ArrowLeft } from 'lucide-react';
import { cn } from '@core/utils/cn';
import { PATHS } from '../../../routes/paths';

const LEGAL_CONTENT = {
    privacy: {
        title: "Privacy Manifesto",
        subtitle: "How we protect and honor your digital identity",
        sections: [
            {
                id: "Introduction",
                title: "The Sanctity of Data",
                icon: Shield,
                content: "At AxeCode, we view data not as a commodity, but as a digital extension of the self. Our commitment to your privacy is absolute. This document outlines our practices regarding the acquisition, protection, and stewardship of your information within the Modern Scholar ecosystem."
            },
            {
                id: "Collection",
                title: "Acquisition of Knowledge",
                icon: FileText,
                content: "We collect information necessary to facilitate your growth. This includes your identity via GitHub OAuth, your educational progress, and your contributions to the digital agora (blogs, articles, and discussions). We do not engage in the sale of personal information to third-party entities."
            },
            {
                id: "Usage",
                title: "The Scholar's Workspace",
                icon: Globe,
                content: "Your data is utilized to personalize your repository. We track course progression and problem submissions to provide a tailored learning experience. Real-time interactions via WebSockets (chats and notifications) are processed to maintain the vitality of the community."
            },
            {
                id: "Protection",
                title: "Digital Fortification",
                icon: Lock,
                content: "We implement advanced encryption and proprietary upload-security strategies to ensure that your private contributions remain private. Our architecture is designed to validate ownership at every layer, from the document service to the edge."
            },
            {
                id: "Rights",
                title: "Your Sovereignty",
                icon: CheckCircle,
                content: "You retain full sovereignty over your data. You have the right to access, rectify, or request the dissolution of your account and associated records at any time. We honor the 'Right to be Forgotten' as a fundamental tenet of digital citizenship."
            }
        ]
    },
    terms: {
        title: "Covenant of Service",
        subtitle: "The principles governing our digital agora",
        sections: [
            {
                id: "Acceptance",
                title: "The Entry Covenant",
                icon: CheckCircle,
                content: "By entering the AxeCode ecosystem, you agree to abide by these principles. This is a binding agreement between you and the platform, designed to ensure a harmonious environment for masters, engineers, and scholars alike."
            },
            {
                id: "Conduct",
                title: "The Digital Agora",
                icon: Users,
                content: "We maintain a standard of excellence. Harassment, plagiarism, and the injection of malicious code are strictly prohibited. The platform reserves the right to review and moderate content via our reporting systems to preserve the integrity of the collective."
            },
            {
                id: "Property",
                title: "The Architect's Rights",
                icon: FileText,
                content: "All content generated by users remains their intellectual property. However, by publishing on AxeCode, you grant the platform a non-exclusive license to host and display your craft to other scholars. Respect for original craftsmanship is paramount."
            },
            {
                id: "Continuity",
                title: "Service Reliability",
                icon: Globe,
                content: "While we strive for perpetual uptime, maintenance is necessary to honor the craft. AxeCode reserves the right to modify or temporarily suspend services for refinement. We are not liable for data loss resulting from unforeseen system anomalies."
            },
            {
                id: "Liability",
                title: "Boundaries of Responsibility",
                icon: Shield,
                content: "AxeCode is provided 'as is'. We are not responsible for the efficacy of the code you learn or the outcomes of your professional endeavors influenced by our repository. Your journey is your own; we are merely the curators of the path."
            }
        ]
    }
};

const LegalSection = ({ section, isActive }) => {
    const Icon = section.icon;
    return (
        <section id={section.id} className="mb-24 scroll-mt-32 group">
            <div className="flex items-center gap-4 mb-6">
                <div className={cn(
                    "p-3 rounded-xl border transition-all duration-300",
                    isActive 
                        ? "bg-accent-primary/10 border-accent-primary/20 text-accent-primary" 
                        : "bg-surface-sunken border-border-subtle text-text-muted group-hover:border-accent-primary/20"
                )}>
                    <Icon size={24} />
                </div>
                <h2 className="text-2xl md:text-3xl font-serif text-text-primary">
                    {section.title}
                </h2>
            </div>
            <p className="text-lg text-text-muted leading-relaxed font-sans max-w-3xl">
                {section.content}
            </p>
        </section>
    );
};

const LegalPage = () => {
    const location = useLocation();
    const type = location.pathname.includes('/terms') ? 'terms' : 'privacy';
    const content = LEGAL_CONTENT[type];
    
    const [activeSection, setActiveSection] = useState(content.sections[0].id);

    useEffect(() => {
        const handleScroll = () => {
            const sections = content.sections.map(s => document.getElementById(s.id));
            const scrollPosition = window.scrollY + 150;

            for (let i = sections.length - 1; i >= 0; i--) {
                const section = sections[i];
                if (section && section.offsetTop <= scrollPosition) {
                    setActiveSection(section.id);
                    break;
                }
            }
        };

        window.addEventListener('scroll', handleScroll);
        return () => window.removeEventListener('scroll', handleScroll);
    }, [content.sections]);

    const scrollToSection = (id) => {
        const element = document.getElementById(id);
        if (element) {
            window.scrollTo({
                top: element.offsetTop - 120,
                behavior: 'smooth'
            });
        }
    };

    return (
        <div className="md:col-span-12 min-h-screen pt-4 pb-20">
            {/* Header Area */}
            <div className="mb-16">
                <Link 
                    to={PATHS.DASHBOARD} 
                    className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-text-muted hover:text-accent-primary transition-colors mb-8 group"
                >
                    <ArrowLeft size={14} className="group-hover:-translate-x-1 transition-transform" />
                    Back to Repository
                </Link>
                <div className="flex flex-col md:flex-row md:items-end justify-between gap-6">
                    <div>
                        <h1 className="text-5xl md:text-6xl font-serif text-text-primary mb-4">
                            {content.title}
                        </h1>
                        <p className="text-xl text-text-muted font-sans italic opacity-70">
                            {content.subtitle}
                        </p>
                    </div>
                    <div className="flex bg-surface-sunken p-1 rounded-xl border border-border-subtle">
                        <Link 
                            to={PATHS.PRIVACY}
                            className={cn(
                                "px-6 py-2 rounded-lg text-xs font-bold uppercase tracking-widest transition-all",
                                type === 'privacy' 
                                    ? "bg-surface-elevated text-accent-primary shadow-sm" 
                                    : "text-text-muted hover:text-text-primary"
                            )}
                        >
                            Privacy
                        </Link>
                        <Link 
                            to={PATHS.TERMS}
                            className={cn(
                                "px-6 py-2 rounded-lg text-xs font-bold uppercase tracking-widest transition-all",
                                type === 'terms' 
                                    ? "bg-surface-elevated text-accent-primary shadow-sm" 
                                    : "text-text-muted hover:text-text-primary"
                            )}
                        >
                            Terms
                        </Link>
                    </div>
                </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-12 gap-16">
                {/* Side Headlines (Classic Side-Nav) */}
                <aside className="lg:col-span-4 hidden lg:block">
                    <div className="sticky top-32 space-y-1">
                        <div className="mb-8 px-4">
                            <span className="text-[10px] font-bold uppercase tracking-[0.3em] text-accent-primary opacity-50">Chapters</span>
                        </div>
                        {content.sections.map((section) => (
                            <button
                                key={section.id}
                                onClick={() => scrollToSection(section.id)}
                                className={cn(
                                    "w-full text-left px-4 py-4 text-sm font-medium transition-all group relative overflow-hidden",
                                    activeSection === section.id 
                                        ? "text-text-primary" 
                                        : "text-text-muted hover:text-text-primary"
                                )}
                            >
                                <span className={cn(
                                    "relative z-10 block transition-transform duration-300",
                                    activeSection === section.id && "translate-x-2"
                                )}>
                                    {section.title}
                                </span>
                                
                                {/* Classic Underline Style */}
                                <div className={cn(
                                    "absolute bottom-0 left-4 right-4 h-px bg-accent-primary transform origin-left transition-transform duration-500",
                                    activeSection === section.id ? "scale-x-100" : "scale-x-0 group-hover:scale-x-50"
                                )} />
                                
                                {activeSection === section.id && (
                                    <div className="absolute left-0 top-1/2 -translate-y-1/2 w-1 h-8 bg-accent-primary rounded-full animate-in fade-in slide-in-from-left-1 duration-300" />
                                )}
                            </button>
                        ))}
                    </div>
                </aside>

                {/* Main Content Area */}
                <article className="lg:col-span-8">
                    <div className="bento-card bg-surface/50 backdrop-blur-sm border-border-subtle/50 p-8 md:p-12">
                        {content.sections.map((section) => (
                            <LegalSection 
                                key={section.id} 
                                section={section} 
                                isActive={activeSection === section.id}
                            />
                        ))}
                    </div>
                </article>
            </div>
            
            {/* Mobile Navigation Header (Fallback for tiny screens) */}
            <div className="lg:hidden fixed bottom-6 left-1/2 -translate-x-1/2 z-50 bg-near-black/90 backdrop-blur-xl border border-white/10 rounded-full px-6 py-3 shadow-2xl flex items-center gap-4">
                <span className="text-[10px] font-bold text-white/50 uppercase tracking-widest">Outline</span>
                <select 
                    value={activeSection}
                    onChange={(e) => scrollToSection(e.target.value)}
                    className="bg-transparent text-white text-xs font-bold outline-none border-none cursor-pointer"
                >
                    {content.sections.map(s => (
                        <option key={s.id} value={s.id} className="text-near-black">{s.title}</option>
                    ))}
                </select>
            </div>
        </div>
    );
};

export default LegalPage;
