import React, { useEffect } from 'react';
import { Loader2, Code2, Terminal, Cpu } from 'lucide-react';
import { useFetchProblem } from '@domain/useCase/useFetchProblem';

/**
 * ProblemTemplatesEditor: Displays auto-generated or configured code templates for the problem.
 * 
 * Note: According to architecture, templates are usually auto-generated 
 * based on the technical signature via backend lifecycles.
 */
export const ProblemTemplatesEditor = ({ problemId }) => {
    const { fetchProblem, problem, loading } = useFetchProblem();

    useEffect(() => {
        if (problemId) {
            fetchProblem(problemId);
        }
    }, [problemId]);

    if (loading && !problem) {
        return (
            <div className="flex flex-col items-center justify-center p-20 text-text-muted animate-pulse">
                <Loader2 className="animate-spin mb-4" size={32} />
                <p className="text-[10px] font-black uppercase tracking-widest">Compiling Template Data...</p>
            </div>
        );
    }

    if (!problem) return null;

    const templates = problem.codeTemplates || [];

    return (
        <div className="animation-fade-in space-y-8">
            <div className="flex items-center gap-4 border-b border-border-subtle pb-6">
                <div className="w-12 h-12 rounded-2xl bg-accent-primary/10 text-accent-primary flex items-center justify-center shadow-inner">
                    <Code2 size={24} />
                </div>
                <div>
                    <h2 className="text-2xl font-serif font-medium tracking-tight text-text-primary">Syntax Archetypes</h2>
                    <p className="text-xs text-text-muted mt-1 uppercase tracking-widest opacity-60">
                        Language-specific starter and wrapper code blocks.
                    </p>
                </div>
            </div>

            {templates.length === 0 ? (
                <div className="bg-surface-sunken/30 border border-dashed border-border-default rounded-3xl p-16 flex flex-col items-center justify-center text-center">
                    <Terminal size={48} className="text-text-muted opacity-20 mb-4" />
                    <p className="font-bold text-text-primary">No templates auto-generated yet.</p>
                    <p className="text-xs text-text-muted mt-2 max-w-sm">
                        Templates are typically generated by the engine once the problem's function signature and parameters are fully specified and saved.
                    </p>
                </div>
            ) : (
                <div className="grid grid-cols-1 gap-6">
                    {templates.map((tpl, index) => (
                        <div key={tpl.id || index} className="bg-surface border border-border-subtle rounded-3xl overflow-hidden shadow-whisper relative group">
                            <div className="absolute top-0 right-0 p-6 opacity-5 pointer-events-none group-hover:opacity-10 transition-opacity text-accent-primary">
                                <Cpu size={120} />
                            </div>
                            
                            <div className="px-8 py-5 border-b border-border-subtle bg-surface-sunken/50 flex items-center justify-between relative z-10">
                                <div className="flex items-center gap-3">
                                    <span className="px-3 py-1 rounded-lg bg-accent-primary/20 text-accent-primary text-[10px] font-black uppercase tracking-widest border border-accent-primary/20">
                                        {tpl.language}
                                    </span>
                                </div>
                            </div>

                            <div className="p-8 grid grid-cols-1 lg:grid-cols-2 gap-8 relative z-10">
                                <div className="space-y-3">
                                    <h4 className="text-[10px] font-bold text-text-muted uppercase tracking-[0.2em]">Starter Code</h4>
                                    <div className="bg-[#0f111a] border border-border-default rounded-2xl p-4 overflow-x-auto">
                                        <pre className="text-xs font-mono text-accent-primary/90 leading-relaxed">
                                            {tpl.starterCode || '// No starter code'}
                                        </pre>
                                    </div>
                                </div>
                                <div className="space-y-3">
                                    <h4 className="text-[10px] font-bold text-text-muted uppercase tracking-[0.2em]">Wrapper Code</h4>
                                    <div className="bg-[#0f111a] border border-border-default rounded-2xl p-4 overflow-x-auto">
                                        <pre className="text-xs font-mono text-accent-emerald/90 leading-relaxed">
                                            {tpl.wrapperCode || '// No wrapper code'}
                                        </pre>
                                    </div>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            )}
        </div>
    );
};
